[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200

board_build.f_cpu = 120000000L         ; CPU Speed: 120 MHz
board_build.filesystem_size = 0        ; Flash Size: 2MB (no FS)

build_flags = 
  -DUSE_TINYUSB
  -Os

lib_ldf_mode = deep+
