[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  # Dependências vitais para a interface gráfica atual
  adafruit/Adafruit GFX Library @ ^1.11.9
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3
  adafruit/Adafruit BusIO @ ^1.14.5
  
  # Dependências para futuras expansões e sensores
  adafruit/Adafruit Unified Sensor @ ^1.1.14
  adafruit/Adafruit BMP280 Library @ ^2.6.8
  adafruit/Adafruit NeoPixel @ ^1.12.0
  
  # Barramentos nativos (SPI, SD, Wire) já estão embutidos no ESP32